### ISSUE TITLE
Index File - Sync and export

### ISSUE THREAD

**Issue by hwoodhouse** [iansinnott/full-text-tabs-forever#2]
Hi Ian,

This is an amazing project, I'm so glad to have found it.
In your README you mention that the index can be exported, but I can't find an obvious way, can you elaborate more on how this might be done?

It would be great to be able to export generally, but I specifically ask in the hope of then being able to sync the file between two devices as I regularly switch between laptops.

**Comment by iansinnott** [comment]
Hey @hwoodhouse thanks for bringing this up;. YES! There is a way to export data, it's just admittedly not discoverable... If you hit Command+K it opens a menu with more options:

<img width="704" alt="screenshot_20240111070341@2x" src="https://github.com/iansinnott/full-text-tabs-forever/assets/3154865/c7a40424-14fd-40c9-8c12-1b812a13503e">

There is currently no sync built in but that's something I've thought about before and was part of the reason to choose VLCN as a database provider. Sync is very much possible and something I'd like to implement for my own use case as well.

I have a working example of such sync in another app: https://github.com/iansinnott/prompta.

**Comment by hwoodhouse** [comment]
Thanks so much for coming back on this - much appreciated!

**Comment by iansinnott** [comment]
Closing this as export is supported and sync is not currently planned.
