### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by Willxiam** [iansinnott/full-text-tabs-forever#3]
I cannot tell you how happy I have been to discover this extension. I would love to have it on Firefox as well. But I understand this might not a small undertaking and do not want to undercut the appreciation I have for what you have done already.

**Comment by iansinnott** [comment]
Thank you for the kind words @Willxiam . 

I'm glad you opened this issue. If there is enough interest I'm happy to make this happen. It's not currently a priority since I'm not using Firefox regularly, but it would be great to support this use case for others.

---

If anyone wants to make a PR It should not be too big a lift, since the web extensoin polyfill should, in theory, unify the browser API: https://github.com/iansinnott/full-text-tabs-forever/blob/736cf458cf30aece0e1a57600066aca6fdd89913/src/background.ts#L1

I initially developed this extension with Firefox and Chrome in mind, however, I ran into issues getting wasm sqlite running with manifest v3 so I removed cross-browser support to simplify the code.

**Comment by daddydevito4253** [comment]
im interested there are many interested in getting an extension for firefox to actually view your whole history as firefoxes view history sucks lol

**Comment by Willxiam** [comment]
@iansinnott PR in this area are a little beyond me unfortunately.  I understand it not being a priority if you are not using it personally. 

@daddydevito4253  I agree.

**Comment by iansinnott** [comment]
See #4 . I have not yet verified this, but in theory we have FF support now (if you build the extension and add it manually).

**Comment by daddydevito4253** [comment]
> See #4 . I have not yet verified this, but in theory we have FF support now (if you build the extension and add it manually).

crap idk how to do that

**Comment by ddxv** [comment]
@daddydevito4253  I was able to get it running by using

`about:debugging` -> This Firefox -> Load Temporary Add-On

Currently not seeing any history, but I think it's probably best to wait for it to show up on the extensions store as that should be very quick.

There are more steps people recommend, like uploading it to the Extensions store to get it signed, but I didn't want to get into that:
https://stackoverflow.com/questions/62237202/firefox-add-ons-how-to-install-my-own-local-add-on-extension-permanently-in-f

**Comment by daddydevito4253** [comment]
what am I loading as extension in Firefox Im not that tech savy just enough to look for more than two seconds and look shit up but the zip didnt work and IDK which manifest it wants to load

**Comment by ddxv** [comment]
> what am I loading as extension in Firefox Im not that tech savy just enough to look for more than two seconds and look shit up but the zip didnt work and IDK which manifest it wants to load

Yeah, probably best to wait for the signed extension from Firefox on the extension store.

**Comment by daddydevito4253** [comment]
aight patience is a  virtue just trying to figure out how to import history to it as it doesnt autograb history prior to download

**Comment by Willxiam** [comment]
@ddxv & @iansinnott @nicholasmullikin  thanks for your effort on this.  I am with @daddydevito4253 not entirely sure what the best practice is to install something temporarily.   I did read that in temporary mode, you have to reinstall the extension everytime you restart firefox. 

I have been waiting /looking for something like this for quite some time.

**Comment by iansinnott** [comment]
Submitted to the FF store.

**Comment by iansinnott** [comment]
Yeah, only submitted not published. 

They have to approve it and I suspect they won't over the weekend unless it's fully automated. But if it was automated they should have approved it already.

**Comment by iansinnott** [comment]
https://addons.mozilla.org/en-US/firefox/addon/full-text-tabs-forever/ 🎉 🍾 

Once installed there's still an extra step to allow it to index your browsing history. You have to go into `about:addons`, find the extension, and enable access. Here's a video of that:

https://github.com/iansinnott/full-text-tabs-forever/assets/3154865/729dedc4-5e7b-4290-8cae-1930a8c81867

**Comment by Willxiam** [comment]
This is great! Thank you so much.

**Comment by ddxv** [comment]
@iansinnott congrats, this works great. Thanks for getting that setup.
