### ISSUE TITLE
Additonal Page Index Control

### ISSUE THREAD

**Issue by Willxiam** [iansinnott/full-text-tabs-forever#6]
If I am missing the setting to do this, let me know. 

It would be nice to be able to blacklist/whitelist domains or specific urls from being indexed both on the fly and also by adding to a list in the settings. 

![image](https://github.com/iansinnott/full-text-tabs-forever/assets/158068941/69741fd6-6f85-4fe6-bbbd-c1cef0570996)

very happy to have this on both chrome and firefox.

**Comment by iansinnott** [comment]
Same as #7 ? That issue is for a blacklist, not a whitelist but it seems similar. 

You can achieve the whitelist via the `"On specific sites"` option above. For a blacklist approach you would need allow on all sites but the plugin would have an interface for blacklisting certain sites.
