### ISSUE TITLE
DB Export Doesn't Work on Firefox

### ISSUE THREAD

**Issue by SCOTU42** [iansinnott/full-text-tabs-forever#8]
When using the "DB: Export..." feature, in Chrome this creates a Json file to save as expected, but in Firefox, nothing happens (except the word "export" gets printed to the web console)

**Comment by iansinnott** [comment]
Hm, thanks for reporting. How big is the database? it will display the estimated size under the search box. Sometimes the export takes a while to build up the JSON file, however, i bet your database isn't too big so this likely isn't the issue. Just want to be sure.

**Comment by SCOTU42** [comment]
I had first tried it almost immediately after installing the extension, when it only had 3 documents.  But now that I can check the exact numbers, I'm at currently:
Documents: 3,498 Fragments: 220,091 Size: 89.16MB

**Comment by future10se** [comment]
I notice there's a PR that's been merged that addresses this issue; might you consider pushing an update to the Firefox Add-ons store?

I could just clone and build the extension myself, but I'd like to export data from my current install which already has a good bit of history. Thank you so much for this tool!

**Comment by iansinnott** [comment]
hey, thanks for the reminder. I will submit a new version to the store shortly

**Comment by iansinnott** [comment]
Should be out. both stores reported it was published.

**Comment by SCOTU42** [comment]
Thank you so much! I confirmed it's now working in FF for me
